
# 窗口相关
WIN_WIDTH = 1280
WIN_HEIGHT = 720
WINDOW_CAPTION = "Card Prisoner"

# 其他
PRICE_PER_CARD = 10

KEYDOWN_INITIAL_INTERVAL = 1  # seconds
DRAW_CARD_TIME_INTERVAL = 0.1  # seconds

# 在普通卡内部的概率分配
A_PROBABILITY = 0.2
B_PROBABILITY = 0.3
C_PROBABILITY = (1 - A_PROBABILITY - B_PROBABILITY)
